# This workflow will install (and optionally cache) dependencies

name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install textual rich openai pexpect pyinstaller pillow certifi

      - name: Run Build
        run: |
          pyinstaller --onefile your_script.py

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install textual rich openai pexpect pyinstaller pillow certifi

      - name: Run Build
        run: |
          pyinstaller --onefile your_script.py
